# Generated by Django 4.1.4 on 2023-01-05 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Additives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suggested', models.CharField(max_length=100)),
                ('maxuse', models.CharField(max_length=100)),
                ('lyephase', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('k_sap', models.DecimalField(decimal_places=4, max_digits=5)),
                ('na_sap', models.DecimalField(decimal_places=4, max_digits=5)),
                ('hard', models.BooleanField()),
                ('iodine', models.IntegerField()),
                ('INS', models.IntegerField()),
                ('lauric', models.IntegerField()),
                ('myristic', models.IntegerField()),
                ('palmitic', models.IntegerField()),
                ('stearic', models.IntegerField()),
                ('ricinoleic', models.IntegerField()),
                ('oleic', models.IntegerField()),
                ('linoleic', models.IntegerField()),
                ('linolenic', models.IntegerField()),
                ('suggested', models.CharField(max_length=100)),
                ('maxuse', models.CharField(max_length=100)),
                ('hardness', models.IntegerField()),
                ('cleansing', models.IntegerField()),
                ('moisturizing', models.IntegerField()),
                ('bubbles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('superfat', models.IntegerField()),
                ('lyetype', models.CharField(max_length=10)),
                ('lyeamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lyeadditives', models.CharField(max_length=100)),
                ('oilname', models.CharField(max_length=100)),
                ('oilamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('additive', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
