# Generated by Django 4.1.4 on 2022-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('k_sap', models.IntegerField()),
                ('na_sap', models.IntegerField()),
                ('hard', models.BooleanField()),
                ('iodine', models.IntegerField()),
                ('INS', models.IntegerField()),
                ('lauric', models.IntegerField()),
                ('myristic', models.IntegerField()),
                ('palmitic', models.IntegerField()),
                ('stearic', models.IntegerField()),
                ('ricinoleic', models.IntegerField()),
                ('oleic', models.IntegerField()),
                ('linoleic', models.IntegerField()),
                ('linolenic', models.IntegerField()),
                ('suggested', models.CharField(max_length=100)),
                ('maxuse', models.CharField(max_length=100)),
                ('hardness', models.IntegerField()),
                ('cleansing', models.IntegerField()),
                ('moisturizing', models.IntegerField()),
                ('bubbles', models.IntegerField()),
            ],
        ),
    ]
