# Generated by Django 4.1.4 on 2022-12-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipemaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Oils',
        ),
    ]
