# Generated by Django 4.1.4 on 2022-12-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemaker', '0002_rename_artist_oils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oils',
            name='k_sap',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='oils',
            name='na_sap',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
