# Generated by Django 4.1.4 on 2022-12-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemaker', '0003_alter_oils_k_sap_alter_oils_na_sap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oils',
            name='k_sap',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='oils',
            name='na_sap',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
