# Generated by Django 4.1.4 on 2023-01-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemaker', '0004_alter_oils_k_sap_alter_oils_na_sap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suggested', models.CharField(max_length=100)),
                ('maxuse', models.CharField(max_length=100)),
                ('lyephase', models.BooleanField()),
            ],
        ),
    ]
