# Generated by Django 4.1.4 on 2023-01-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemaker', '0005_additives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('superfat', models.IntegerField()),
                ('lyetype', models.CharField(max_length=10)),
                ('lyeamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lyeadditives', models.CharField(max_length=100)),
                ('oilname', models.CharField(max_length=100)),
                ('oilamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('additive', models.CharField(max_length=100)),
            ],
        ),
    ]
